[build]
  publish = "static"

[dev]
  publish = "static"

[functions]
  # Sets a custom directory for Netlify Functions
  directory = "functions"

  # Specifies `esbuild` for functions bundling
  node_bundler = "esbuild"
  
  # Flags "package-1" as an external node module for all functions
  external_node_modules = ["@ffmpeg/ffmpeg"]